//! 构建脚本：预解析 Live2D motion/expression 元数据和 model_manifest.json，嵌入二进制。
//!
//! 扫描 public/ 下每个角色的 .motion3.json、.exp3.json 和 model_manifest.json 文件，
//! 提取元数据（时长、帧率、参数数量等），生成 Rust 静态数据。
//! 这样启用 Tauri encryptResources 后，运行时无需读取文件内容即可获取元数据。

use serde::Deserialize;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

// ===== 与 resource_loader.rs 中相同的解析结构 =====

#[derive(Debug, Default, Deserialize)]
struct MotionMeta {
    #[serde(default, rename = "Duration")]
    duration: f64,
    #[serde(default = "default_fps", rename = "Fps")]
    fps: u32,
    #[serde(default = "default_loop", rename = "Loop")]
    is_loop: bool,
    #[serde(default, rename = "TotalFrameCount")]
    total_frames: u64,
}

fn default_fps() -> u32 {
    30
}
fn default_loop() -> bool {
    true
}

#[derive(Debug, Default, Deserialize)]
struct MotionFile {
    #[serde(default)]
    meta: MotionMeta,
    #[serde(default, rename = "Curves")]
    curves: Vec<serde_json::Value>,
}

#[derive(Debug, Default, Deserialize)]
struct ExpressionFile {
    #[serde(default, rename = "ExpressionName")]
    expression_name: Option<String>,
    #[serde(default, rename = "Parameters")]
    parameters: Vec<serde_json::Value>,
}

// ===== 预解析结果结构 =====

struct MotionMetaParsed {
    name: String,
    duration: f64,
    fps: u32,
    is_loop: bool,
    total_frames: u64,
    curve_count: usize,
}

struct ExpressionMetaParsed {
    name: String,
    expression_id: String,
    parameter_count: usize,
}

struct CharManifestParsed {
    char_id: String,
    json_content: String,
}

fn main() {
    // Tauri 构建钩子：生成 Windows manifest（Common-Controls v6）、嵌入图标等
    tauri_build::build();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("manifest_data.rs");

    let manifest = generate_manifest();
    fs::write(&dest_path, manifest).expect("Failed to write manifest_data.rs");

    generate_asset_key(&out_dir);
    generate_bundle_index(&out_dir);

    println!("cargo:rerun-if-changed=../public");
    println!("cargo:rerun-if-changed=vivian.bundle.enc");
    println!("cargo:rerun-if-changed=vivian.bundle.index.json");
}

/// 读取 vivian.bundle.index.json，生成 OUT_DIR/bundle_index.rs
///
/// 索引 JSON 由 scripts/encrypt-assets.mjs 生成，包含压缩格式和每个文件的路径/偏移/大小。
/// 运行时由 bundle_reader.rs include! 引入，无需读磁盘即可查找资源。
fn generate_bundle_index(out_dir: &str) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let index_file = Path::new(&manifest_dir).join("vivian.bundle.index.json");

    let (format, entries): (String, Vec<(String, u64, u64)>) = if index_file.exists() {
        let content = fs::read_to_string(&index_file)
            .expect("Failed to read vivian.bundle.index.json");
        let json: serde_json::Value = serde_json::from_str(&content)
            .expect("Failed to parse vivian.bundle.index.json");

        let format = json["format"]
            .as_str()
            .unwrap_or("zstd")
            .to_string();

        let entries: Vec<(String, u64, u64)> = json["entries"]
            .as_array()
            .expect("bundle index entries must be array")
            .iter()
            .map(|e| {
                let path = e["path"].as_str().expect("entry path").to_string();
                let offset = e["offset"].as_u64().expect("entry offset");
                let size = e["size"].as_u64().expect("entry size");
                (path, offset, size)
            })
            .collect();

        (format, entries)
    } else {
        // dev 模式或未运行加密脚本：空索引
        println!("cargo:warning=vivian.bundle.index.json not found; generating empty index (run `npm run encrypt:assets` before release build)");
        ("zstd".to_string(), vec![])
    };

    let dest = Path::new(out_dir).join("bundle_index.rs");
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n");
    code.push_str("// Bundle 索引（由 scripts/encrypt-assets.mjs 生成）\n\n");

    code.push_str(&format!(
        "pub const BUNDLE_COMPRESSION_FORMAT: &str = \"{}\";\n\n",
        format
    ));

    code.push_str("pub const BUNDLE_ENTRIES: &[crate::bundle_reader::BundleEntry] = &[\n");
    for (path, offset, size) in &entries {
        code.push_str(&format!(
            "    crate::bundle_reader::BundleEntry {{ path: \"{}\", offset: {}, size: {} }},\n",
            path, offset, size
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("Failed to write bundle_index.rs");
}

/// 读取或生成 AES 密钥，拆分多段以不同方式混淆后写入 OUT_DIR/asset_key.rs
///
/// 密钥来源: src-tauri/asset_key.bin（由 scripts/encrypt-assets.mjs 生成，不入库）
/// 32 字节密钥拆成 4 段，每段采用不同变换（XOR / 反转+XOR / XOR+加法偏移 / XOR+字节循环移位），
/// 避免单一完整密钥常量出现在二进制中。运行时由 asset_crypto::derive_key 多步还原。
fn generate_asset_key(out_dir: &str) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let key_file = Path::new(&manifest_dir).join("asset_key.bin");

    let key_bytes: [u8; 32] = if key_file.exists() {
        let data = fs::read(&key_file).expect("Failed to read asset_key.bin");
        if data.len() != 32 {
            panic!("asset_key.bin 长度异常: {} 字节 (期望 32)，请删除后重新运行 npm run encrypt:assets", data.len());
        }
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&data);
        arr
    } else {
        println!("cargo:warning=asset_key.bin not found; using zero key (run `npm run encrypt:assets` before release build)");
        [0u8; 32]
    };

    // 编译期 PRNG（基于时间戳种子，每次编译生成不同的掩码/参数）
    let mut state = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x1234567890ABCDEF);
    let mut next_u8 = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        (state >> 33) as u8
    };

    // 4 个掩码（每段一个）+ 2 个变换参数
    let mut masks = [[0u8; 8]; 4];
    for m in masks.iter_mut() {
        for i in 0..8 {
            m[i] = next_u8();
        }
    }
    let offset_c: u8 = next_u8();
    let rot_d: u8 = next_u8() % 8;

    // 拆分密钥为 4 段
    let mut segs = [[0u8; 8]; 4];
    for i in 0..4 {
        segs[i].copy_from_slice(&key_bytes[i * 8..(i + 1) * 8]);
    }

    // 段 A: XOR mask_a
    let seg_a_obf: [u8; 8] = {
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = segs[0][i] ^ masks[0][i];
        }
        o
    };
    // 段 B: 先反转再 XOR mask_b
    let seg_b_obf: [u8; 8] = {
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = segs[1][7 - i] ^ masks[1][i];
        }
        o
    };
    // 段 C: XOR mask_c 后加偏移 offset_c
    let seg_c_obf: [u8; 8] = {
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = (segs[2][i] ^ masks[2][i]).wrapping_add(offset_c);
        }
        o
    };
    // 段 D: 先字节循环右移 rot_d 位，再 XOR mask_d
    let seg_d_obf: [u8; 8] = {
        let n = rot_d as usize;
        let mut y = [0u8; 8];
        for i in 0..8 {
            y[i] = segs[3][(i + n) % 8];
        }
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = y[i] ^ masks[3][i];
        }
        o
    };

    let dest = Path::new(out_dir).join("asset_key.rs");
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n");
    code.push_str("// AES-256 key split into 4 segments with different obfuscation transforms\n\n");

    let write_arr8 = |code: &mut String, name: &str, arr: &[u8; 8]| {
        code.push_str(&format!("pub const {}: [u8; 8] = [", name));
        for &b in arr.iter() {
            code.push_str(&format!(" 0x{:02x},", b));
        }
        code.push_str(" ];\n");
    };

    write_arr8(&mut code, "SEG_A_OBF", &seg_a_obf);
    write_arr8(&mut code, "SEG_B_OBF", &seg_b_obf);
    write_arr8(&mut code, "SEG_C_OBF", &seg_c_obf);
    write_arr8(&mut code, "SEG_D_OBF", &seg_d_obf);
    write_arr8(&mut code, "MASK_A", &masks[0]);
    write_arr8(&mut code, "MASK_B", &masks[1]);
    write_arr8(&mut code, "MASK_C", &masks[2]);
    write_arr8(&mut code, "MASK_D", &masks[3]);
    code.push_str(&format!("pub const OFFSET_C: u8 = 0x{:02x};\n", offset_c));
    code.push_str(&format!("pub const ROT_D: u8 = {};\n", rot_d));

    fs::write(&dest, code).expect("Failed to write asset_key.rs");
}

fn generate_manifest() -> String {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let public_dir = Path::new(&manifest_dir).join("..").join("public");

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs — do not edit manually\n");
    output.push_str("// Pre-parsed Live2D motion, expression, and manifest data\n\n");

    // 共享类型定义
    output.push_str(
        r#"
#[derive(Debug, Clone)]
pub struct PreParsedMotion {
    pub name: &'static str,
    pub duration: f64,
    pub fps: u32,
    pub is_loop: bool,
    pub total_frames: u64,
    pub curve_count: usize,
}

#[derive(Debug, Clone)]
pub struct PreParsedExpression {
    pub name: &'static str,
    pub expression_id: &'static str,
    pub parameter_count: usize,
}

"#,
    );

    if !public_dir.exists() {
        output.push_str("// public/ directory not found — no pre-parsed data generated\n");
        return output;
    }

    // 扫描每个角色目录
    let char_dirs = match fs::read_dir(&public_dir) {
        Ok(entries) => entries
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.path())
            .collect::<Vec<_>>(),
        Err(_) => return output,
    };

    let mut all_manifests: Vec<CharManifestParsed> = Vec::new();

    for char_dir in &char_dirs {
        let char_name = match char_dir.file_name().and_then(|n| n.to_str()) {
            Some(name) => name.to_string(),
            None => continue,
        };

        // 跳过非角色目录
        if char_name == "expression" || char_name == "world-bg" || char_name == "assets" || char_name == "fonts" {
            continue;
        }

        let motions = parse_motions(char_dir);
        let expressions = parse_expressions(char_dir);
        let manifest_json = parse_manifest(char_dir);

        if motions.is_empty() && expressions.is_empty() && manifest_json.is_none() {
            continue;
        }

        // 嵌入 manifest JSON
        if let Some(json) = manifest_json {
            all_manifests.push(CharManifestParsed {
                char_id: char_name.clone(),
                json_content: json,
            });
        }

        output.push_str(&format!("pub mod {} {{\n", sanitize_ident(&char_name)));
        output.push_str("    use super::{PreParsedMotion, PreParsedExpression};\n\n");

        // 动作列表
        output.push_str(&format!(
            "    pub const MOTIONS: &[PreParsedMotion] = &[\n"
        ));
        for m in &motions {
            let dur = if (m.duration - m.duration.round()).abs() < f64::EPSILON {
                format!("{:.1}", m.duration)
            } else {
                format!("{}", m.duration)
            };
            output.push_str(&format!(
                "        PreParsedMotion {{ name: \"{}\", duration: {}, fps: {}, is_loop: {}, total_frames: {}, curve_count: {} }},\n",
                escape_str(&m.name),
                dur,
                m.fps,
                m.is_loop,
                m.total_frames,
                m.curve_count,
            ));
        }
        output.push_str("    ];\n\n");

        // 表情列表
        output.push_str(&format!(
            "    pub const EXPRESSIONS: &[PreParsedExpression] = &[\n"
        ));
        for e in &expressions {
            output.push_str(&format!(
                "        PreParsedExpression {{ name: \"{}\", expression_id: \"{}\", parameter_count: {} }},\n",
                escape_str(&e.name),
                escape_str(&e.expression_id),
                e.parameter_count,
            ));
        }
        output.push_str("    ];\n");
        output.push_str("}\n\n");
    }

    // === manifest JSON 嵌入 ===
    output.push_str("// ---- Embedded model_manifest.json content ----\n\n");
    for mf in &all_manifests {
        output.push_str(&format!(
            "pub const {}_MANIFEST_JSON: &str = r#\"{}\"#;\n\n",
            sanitize_ident(&mf.char_id).to_uppercase(),
            mf.json_content
        ));
    }

    // === 查找函数 ===
    output.push_str(
        r#"
/// 按角色 ID 查找预解析的动作元数据
pub fn get_pre_parsed_motions(char_id: &str) -> &[PreParsedMotion] {
    match char_id {
"#,
    );

    for char_dir in &char_dirs {
        let char_name = char_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("");
        if char_name == "expression" || char_name == "world-bg" || char_name == "assets" || char_name == "fonts" {
            continue;
        }
        output.push_str(&format!(
            "        \"{}\" => {}::MOTIONS,\n",
            escape_str(char_name),
            sanitize_ident(char_name),
        ));
    }

    output.push_str(
        r#"        _ => &[],
    }
}

/// 按角色 ID 查找预解析的表情元数据
pub fn get_pre_parsed_expressions(char_id: &str) -> &[PreParsedExpression] {
    match char_id {
"#,
    );

    for char_dir in &char_dirs {
        let char_name = char_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("");
        if char_name == "expression" || char_name == "world-bg" || char_name == "assets" || char_name == "fonts" {
            continue;
        }
        output.push_str(&format!(
            "        \"{}\" => {}::EXPRESSIONS,\n",
            escape_str(char_name),
            sanitize_ident(char_name),
        ));
    }

    output.push_str(
        r#"        _ => &[],
    }
}

/// 按角色 ID 查找预解析的 model_manifest.json 内容
pub fn get_embedded_manifest_json(char_id: &str) -> Option<&'static str> {
    match char_id {
"#,
    );

    for mf in &all_manifests {
        output.push_str(&format!(
            "        \"{}\" => Some({}_MANIFEST_JSON),\n",
            escape_str(&mf.char_id),
            sanitize_ident(&mf.char_id).to_uppercase(),
        ));
    }

    output.push_str(
        r#"        _ => None,
    }
}

/// 列出所有有嵌入 manifest 的角色 ID
pub fn list_embedded_manifest_ids() -> &'static [&'static str] {
    &[
"#,
    );

    for mf in &all_manifests {
        output.push_str(&format!("        \"{}\",\n", escape_str(&mf.char_id)));
    }

    output.push_str(
        r#"    ]
}

/// 按角色 ID 和动作名查找单个预解析动作元数据
pub fn get_pre_parsed_motion_meta(char_id: &str, motion_name: &str) -> Option<PreParsedMotion> {
    let motions = get_pre_parsed_motions(char_id);
    motions.iter().find(|m| m.name == motion_name).cloned()
}
"#,
    );

    output
}

fn parse_motions(dir: &Path) -> Vec<MotionMetaParsed> {
    let mut motions = BTreeMap::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                for sub in parse_motions(&path) {
                    motions.insert(sub.name.clone(), sub);
                }
                continue;
            }
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if name.ends_with(".motion3.json") {
                let base_name = name.replace(".motion3.json", "").replace(".mtn", "");
                if let Ok(content) = fs::read_to_string(&path) {
                    if let Ok(file) = serde_json::from_str::<MotionFile>(&content) {
                        motions.insert(
                            base_name.clone(),
                            MotionMetaParsed {
                                name: base_name,
                                duration: file.meta.duration,
                                fps: file.meta.fps,
                                is_loop: file.meta.is_loop,
                                total_frames: file.meta.total_frames,
                                curve_count: file.curves.len(),
                            },
                        );
                    }
                }
            }
        }
    }
    motions.into_values().collect()
}

fn parse_expressions(dir: &Path) -> Vec<ExpressionMetaParsed> {
    let mut expressions = BTreeMap::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                for sub in parse_expressions(&path) {
                    expressions.insert(sub.name.clone(), sub);
                }
                continue;
            }
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if name.ends_with(".exp3.json") {
                let base_name = name.replace(".exp3.json", "");
                let stem = Path::new(name)
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or(&base_name)
                    .to_string();
                if let Ok(content) = fs::read_to_string(&path) {
                    if let Ok(file) = serde_json::from_str::<ExpressionFile>(&content) {
                        let expression_id = file.expression_name.unwrap_or_else(|| stem.clone());
                        expressions.insert(
                            base_name,
                            ExpressionMetaParsed {
                                name: stem,
                                expression_id,
                                parameter_count: file.parameters.len(),
                            },
                        );
                    }
                }
            }
        }
    }
    expressions.into_values().collect()
}

fn parse_manifest(dir: &Path) -> Option<String> {
    let manifest_path = dir.join("model_manifest.json");
    fs::read_to_string(&manifest_path).ok()
}

fn sanitize_ident(name: &str) -> String {
    let mut result = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' {
            for lc in c.to_lowercase() {
                result.push(lc);
            }
        } else {
            result.push('_');
        }
    }
    result
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

// 防止未使用警告
#[allow(dead_code)]
fn _unused(_: PathBuf) {}
