//! 构建脚本：嵌入 chibi 动作词汇表 + 生成 bundle 索引与密钥混淆数据。
//!
//! - 生成 OUT_DIR/manifest_data.rs：把 `src/chibi/animations.json` 原样嵌入二进制。
//!   后端据此产出动作名清单、情绪映射与空闲/事件触发，与前端渲染器共用同一份声明，
//!   保证 prompt 里列出的动作与前端真正能播的动作是同一套名字。
//!   之所以不在运行时读文件：这份词汇表既不是运行时素材也不该进安装包，
//!   构建期固化最省事；
//! - 生成 OUT_DIR/bundle_index.rs：解析 vivian.bundle.index.json（VBL2 索引），
//!   运行时无需读磁盘即可查找加密资源；
//! - 生成 OUT_DIR/asset_key.rs：AES 密钥拆分混淆嵌入。

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Tauri 构建钩子：生成 Windows manifest（Common-Controls v6）、嵌入图标等
    tauri_build::build();

    // comctl32 delay-load：依赖树静态导入 TaskDialogIndirect（comctl32 v6 独有），
    // 但 SxS 清单只由 tauri_build 嵌入 bin 目标（经 rustc-link-arg-bins 链接的
    // 资源），lib 测试 exe 拿不到 v6 清单 → 加载器绑到 5.82 兼容导出集，
    // 测试进程 0xC0000139 起不来。delay-load 把 comctl32 的绑定从加载期推迟到
    // 首次调用：主程序不受影响（manifest 照常在运行时解析 v6），测试 exe
    // 不调用 GUI API、根本不加载 comctl32。仅 MSVC 工具链认识 /DELAYLOAD。
    if env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("msvc") {
        println!("cargo:rustc-link-arg=/DELAYLOAD:comctl32.dll");
        println!("cargo:rustc-link-arg=delayimp.lib");
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("manifest_data.rs");

    let manifest = generate_chibi_vocab_data();
    fs::write(&dest_path, manifest).expect("Failed to write manifest_data.rs");

    generate_asset_key(&out_dir);
    generate_bundle_index(&out_dir);

    println!("cargo:rerun-if-changed=../src/chibi/animations.json");
    println!("cargo:rerun-if-changed=../public");
    println!("cargo:rerun-if-changed=vivian.bundle.enc");
    println!("cargo:rerun-if-changed=vivian.bundle.index.json");
}

/// 生成 manifest_data.rs：嵌入 chibi 动作词汇表原文。
fn generate_chibi_vocab_data() -> String {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs — do not edit manually\n");
    output.push_str("// Embedded chibi animations vocabulary\n\n");
    output.push_str(&chibi_vocab_section(&manifest_dir));
    output
}

/// 嵌入 Q 版动作词汇表原文。
///
/// 词汇表放在 `src/chibi/animations.json`，前端渲染器直接 import 同一份文件，
/// 这里只把它原样搬进二进制：后端据此产出动作名清单、情绪映射与空闲触发，
/// 保证 prompt 里列出的动作与前端真正能播的动作是同一套名字。
///
/// 之所以不做成运行时读文件：`public/` 走的是加密 bundle 与白名单复制两条路，
/// 而这份词汇表既不是运行时素材也不该进安装包，构建期固化最省事。
fn chibi_vocab_section(manifest_dir: &str) -> String {
    let vocab_path = Path::new(manifest_dir)
        .join("..")
        .join("src")
        .join("chibi")
        .join("animations.json");

    let json = match fs::read_to_string(&vocab_path) {
        Ok(json) => json,
        Err(e) => {
            println!(
                "cargo:warning=未能读取 {}（{e}），Q 版动作词汇表将为空，桌宠动作名清单与情绪映射不会生效",
                vocab_path.display()
            );
            return String::new();
        }
    };

    if serde_json::from_str::<serde_json::Value>(&json).is_err() {
        println!(
            "cargo:warning={} 不是合法 JSON，Q 版动作词汇表将为空",
            vocab_path.display()
        );
        return String::new();
    }

    format!(
        "\n/// Q 版桌宠动作词汇表原文（`src/chibi/animations.json`）\n\
         ///\n\
         /// 前端渲染器与后端动作名清单共用同一份声明，避免两侧词汇各自硬编码后漂移。\n\
         pub const CHIBI_ANIMATIONS_JSON: &str = {};\n\n\
         /// 取 Q 版动作词汇表原文；构建期未嵌入时返回 `None`。\n\
         pub fn chibi_animations_json() -> Option<&'static str> {{\n\
         \x20   if CHIBI_ANIMATIONS_JSON.is_empty() {{ None }} else {{ Some(CHIBI_ANIMATIONS_JSON) }}\n\
         }}\n",
        raw_string_literal(&json)
    )
}

/// 把内容包成不会提前闭合的 Rust 原生字符串字面量。
///
/// 固定用 `r#"…"#` 会在内容里出现 `"#` 时截断，进而生成语法错误的代码；
/// 这里按内容实际出现的连续井号数提高围栏。
fn raw_string_literal(content: &str) -> String {
    let mut hashes = 1usize;
    loop {
        let fence = format!("\"{}", "#".repeat(hashes));
        if !content.contains(&fence) {
            break;
        }
        hashes += 1;
    }
    let hashes = "#".repeat(hashes);
    format!("r{hashes}\"{content}\"{hashes}")
}

/// 读取 vivian.bundle.index.json，生成 OUT_DIR/bundle_index.rs
///
/// 索引 JSON 由资源加密步骤生成（VBL2 按需解压格式），
/// 包含每个文件的路径/密文偏移/密文长度/明文长度。
/// 运行时由 bundle_reader.rs include! 引入，无需读磁盘即可查找资源。
fn generate_bundle_index(out_dir: &str) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let index_file = Path::new(&manifest_dir).join("vivian.bundle.index.json");

    let entries: Vec<(String, u64, u64, u64)> = if index_file.exists() {
        let content = fs::read_to_string(&index_file)
            .expect("Failed to read vivian.bundle.index.json");
        let json: serde_json::Value = serde_json::from_str(&content)
            .expect("Failed to parse vivian.bundle.index.json");

        if json["version"].as_u64() != Some(2) {
            panic!(
                "vivian.bundle.index.json 为旧版 VBL1 格式，请重新生成 VBL2 按需解压格式的 bundle 索引（资源加密步骤产物）"
            );
        }

        json["entries"]
            .as_array()
            .expect("bundle index entries must be array")
            .iter()
            .map(|e| {
                let path = e["path"].as_str().expect("entry path").to_string();
                let offset = e["offset"].as_u64().expect("entry offset");
                let size = e["size"].as_u64().expect("entry size");
                let plain_size = e["plainSize"].as_u64().expect("entry plainSize");
                (path, offset, size, plain_size)
            })
            .collect()
    } else {
        // dev 模式或未运行加密脚本：空索引
        println!("cargo:warning=vivian.bundle.index.json not found; generating empty index (regenerate the bundle index via the asset-encryption step before a release build)");
        vec![]
    };

    let dest = Path::new(out_dir).join("bundle_index.rs");
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n");
    code.push_str("// Bundle 索引（由资源加密步骤生成）\n\n");

    code.push_str("pub const BUNDLE_ENTRIES: &[crate::bundle_reader::BundleEntry] = &[\n");
    for (path, offset, size, plain_size) in &entries {
        code.push_str(&format!(
            "    crate::bundle_reader::BundleEntry {{ path: \"{}\", offset: {}, size: {}, plain_size: {} }},\n",
            path, offset, size, plain_size
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("Failed to write bundle_index.rs");
}

/// 读取或生成 AES 密钥，拆分多段以不同方式混淆后写入 OUT_DIR/asset_key.rs
///
/// 密钥来源: src-tauri/asset_key.bin（由资源加密步骤生成，不入库）
/// 32 字节密钥拆成 4 段，每段采用不同变换（XOR / 反转+XOR / XOR+加法偏移 / XOR+字节循环移位），
/// 避免单一完整密钥常量出现在二进制中。运行时由 asset_crypto::derive_key 多步还原。
fn generate_asset_key(out_dir: &str) {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let key_file = Path::new(&manifest_dir).join("asset_key.bin");

    let key_bytes: [u8; 32] = if key_file.exists() {
        let data = fs::read(&key_file).expect("Failed to read asset_key.bin");
        if data.len() != 32 {
            panic!("asset_key.bin 长度异常: {} 字节 (期望 32)，请检查资源加密步骤生成的密钥文件", data.len());
        }
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&data);
        arr
    } else {
        println!("cargo:warning=asset_key.bin not found; using zero key (regenerate the key via the asset-encryption step before a release build)");
        [0u8; 32]
    };

    // 编译期 PRNG（基于时间戳种子，每次编译生成不同的掩码/参数）
    let mut state = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x1234567890ABCDEF);
    let mut next_u8 = || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        (state >> 33) as u8
    };

    // 4 个掩码（每段一个）+ 2 个变换参数
    let mut masks = [[0u8; 8]; 4];
    for m in masks.iter_mut() {
        for i in 0..8 {
            m[i] = next_u8();
        }
    }
    let offset_c: u8 = next_u8();
    let rot_d: u8 = next_u8() % 8;

    // 拆分密钥为 4 段
    let mut segs = [[0u8; 8]; 4];
    for i in 0..4 {
        segs[i].copy_from_slice(&key_bytes[i * 8..(i + 1) * 8]);
    }

    // 段 A: XOR mask_a
    let seg_a_obf: [u8; 8] = {
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = segs[0][i] ^ masks[0][i];
        }
        o
    };
    // 段 B: 先反转再 XOR mask_b
    let seg_b_obf: [u8; 8] = {
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = segs[1][7 - i] ^ masks[1][i];
        }
        o
    };
    // 段 C: XOR mask_c 后加偏移 offset_c
    let seg_c_obf: [u8; 8] = {
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = (segs[2][i] ^ masks[2][i]).wrapping_add(offset_c);
        }
        o
    };
    // 段 D: 先字节循环右移 rot_d 位，再 XOR mask_d
    let seg_d_obf: [u8; 8] = {
        let n = rot_d as usize;
        let mut y = [0u8; 8];
        for i in 0..8 {
            y[i] = segs[3][(i + n) % 8];
        }
        let mut o = [0u8; 8];
        for i in 0..8 {
            o[i] = y[i] ^ masks[3][i];
        }
        o
    };

    let dest = Path::new(out_dir).join("asset_key.rs");
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n");
    code.push_str("// AES-256 key split into 4 segments with different obfuscation transforms\n\n");

    let write_arr8 = |code: &mut String, name: &str, arr: &[u8; 8]| {
        code.push_str(&format!("pub const {}: [u8; 8] = [", name));
        for &b in arr.iter() {
            code.push_str(&format!(" 0x{:02x},", b));
        }
        code.push_str(" ];\n");
    };

    write_arr8(&mut code, "SEG_A_OBF", &seg_a_obf);
    write_arr8(&mut code, "SEG_B_OBF", &seg_b_obf);
    write_arr8(&mut code, "SEG_C_OBF", &seg_c_obf);
    write_arr8(&mut code, "SEG_D_OBF", &seg_d_obf);
    write_arr8(&mut code, "MASK_A", &masks[0]);
    write_arr8(&mut code, "MASK_B", &masks[1]);
    write_arr8(&mut code, "MASK_C", &masks[2]);
    write_arr8(&mut code, "MASK_D", &masks[3]);
    code.push_str(&format!("pub const OFFSET_C: u8 = 0x{:02x};\n", offset_c));
    code.push_str(&format!("pub const ROT_D: u8 = {};\n", rot_d));

    fs::write(&dest, code).expect("Failed to write asset_key.rs");
}
