import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { webcrypto } from 'node:crypto';
const calls=[];
globalThis.__desktopCalls=calls;
globalThis.__desktopInvoke=async(name,args)=>{
  calls.push({name,args});
  if(name==='companion_desktop_context')return {shortcuts:[]};
  if(name==='companion_screen_analyze')return {handled:true};
  return {};
};
const oldWindow=globalThis.window, oldCrypto=Object.getOwnPropertyDescriptor(globalThis,'crypto');
globalThis.window={location:{search:''}};
Object.defineProperty(globalThis,'crypto',{configurable:true,value:webcrypto});
const bundle=await build({entryPoints:['src/components/DesktopAssistantWindow.tsx'],bundle:true,write:false,platform:'node',format:'esm',loader:{'.css':'empty'},plugins:[{name:'desktop-fixtures',setup(b){
 b.onResolve({filter:/^react$|^react\/jsx-runtime$/},a=>({path:a.path,namespace:'fixture'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='react'?
  `export const useState=value=>[globalThis.__desktopStates.length?globalThis.__desktopStates.shift():value,value=>globalThis.__desktopUpdates.push(value)]; export const useRef=value=>({current:value}); export const useEffect=effect=>globalThis.__desktopEffects.push(effect); export const useCallback=fn=>fn;`
  :`export const jsx=(type,props)=>({type,props});export const jsxs=jsx;export const Fragment='fragment';`}));
 b.onResolve({filter:/^@tauri-apps\/api\//},a=>({path:a.path,namespace:'native'}));
 b.onLoad({filter:/.*/,namespace:'native'},()=>({contents:`export const invoke=(...args)=>globalThis.__desktopInvoke(...args);export const emit=async(...args)=>{globalThis.__desktopCalls.push({name:'emit',args});};export const listen=async()=>()=>{};export const getCurrentWindow=()=>({hide:async()=>{globalThis.__desktopCalls.push({name:'hide'});},show:async()=>{globalThis.__desktopCalls.push({name:'show'});}});`}));
 b.onResolve({filter:/^react-i18next$/},a=>({path:a.path,namespace:'i18n'}));
 b.onLoad({filter:/.*/,namespace:'i18n'},()=>({contents:`export const useTranslation=()=>({i18n:{language:'zh-CN'}});`}));
 b.onResolve({filter:/^lucide-react$/},a=>({path:a.path,namespace:'icons'}));
 b.onLoad({filter:/.*/,namespace:'icons'},()=>({contents:`export const ArrowLeft=()=>null, ArrowUpRight=()=>null, ChevronRight=()=>null, CloudSun=()=>null, Dice5=()=>null, Heart=()=>null, Settings=()=>null, House=()=>null, LayoutGrid=()=>null, Mic=()=>null, Monitor=()=>null, Music2=()=>null, NotebookPen=()=>null, Plus=()=>null, Rocket=()=>null, Sparkles=()=>null, Trash2=()=>null;`}));
}}]});
const {default:Page}=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
function render(tab,preference='',props={}){
 globalThis.__desktopEffects=[];
 globalThis.__desktopUpdates=[];
 globalThis.__desktopStates=['nana',{shortcuts:[],quiet_reason:null},tab,false,'','', 'note text',preference,'','','website'];
 return Page(props);
}
const text=node=>node==null?'':Array.isArray(node)?node.map(text).join(''):typeof node==='object'?text(node.props?.children):String(node);
function find(node,match){if(node==null)return null;if(Array.isArray(node)){for(const n of node){const found=find(n,match);if(found)return found;}return null;}if(typeof node==='object'){if(match(node))return node;return find(node.props?.children,match);}return null;}
let page;
page=render('preferences','I prefer quiet work');
await find(page,n=>n.type==='button'&&text(n)==='记住').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(calls.find(c=>c.name==='companion_remember_preference').args,{characterId:'nana',content:'I prefer quiet work'});
calls.length=0;
page=render('notes');
await find(page,n=>n.type==='button'&&text(n)==='保存').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(calls.find(c=>c.name==='user_quick_notes_save').args,{content:'note text'});
assert.equal(calls.filter(c=>c.name==='create_notebook'||(c.name==='emit'&&c.args[0]==='companion:interaction')).length,0,'user notes never become pet notebooks or trigger speech on save');
const noteList = find(page,n=>typeof n.type==='function'&&n.type.name==='UserQuickNotes');
assert.ok(noteList);
globalThis.__desktopStates=[[{id:'user-note',title:'灵感',content:'我的灵感',created_at:1}],false,''];
globalThis.__desktopEffects=[];
const notesView=noteList.type();
const notesCleanup=globalThis.__desktopEffects[0]();
await new Promise(resolve=>setImmediate(resolve));
assert.equal(calls.find(c=>c.name==='user_quick_notes_list').args,undefined,'the user notebook is shared and has no character scope');
assert.ok(text(notesView).includes('我的灵感'));
await find(notesView,n=>n.type==='button'&&n.props['aria-label']==='删除随手记').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(calls.find(c=>c.name==='user_quick_notes_delete').args,{id:'user-note'});
assert.equal(calls.filter(c=>c.name==='list_notebooks'||c.name==='get_notebook_detail').length,0);
notesCleanup();
calls.length=0;
page=render('games');
await find(page,n=>n.type==='button'&&text(n)==='🎲').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.equal(calls.filter(c=>c.name.startsWith('companion_')).length,0,'games never invoke models');
calls.length=0;
page=render('games');
await find(page,n=>n.type==='button'&&text(n)==='✊').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
const rps = calls.find(c=>c.name==='emit' && c.args[0]==='companion:interaction').args[1];
const companionHand = rps.content.split(' vs ')[1].split(' · ')[0];
assert.equal(rps.motion, {'✊':'rps-rock','✋':'rps-paper','✌️':'rps-scissors'}[companionHand]);
assert.equal(calls.filter(c=>c.name.startsWith('companion_')).length,0,'RPS never invokes models');
calls.length=0;
page=render('daily');
assert.equal(calls.length,0,'rendering does not capture the screen');
await find(page,n=>n.type==='button'&&n.props['data-action']==='screen').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(calls.filter(c=>['hide','companion_screen_analyze','show'].includes(c.name)).map(c=>c.name),['companion_screen_analyze']);
assert.equal(calls.find(c=>c.name==='companion_screen_analyze').args.characterId,'nana');
assert.equal(calls.filter(c=>c.name==='emit' && ['companion:interaction','chat:assistant_message'].includes(c.args[0])).length,0,'screenshot replies arrive only through the main dialogue stream, never as raw recognition');
const normalInvoke=globalThis.__desktopInvoke;
globalThis.__desktopInvoke=async(name,args)=>{if(name==='companion_screen_analyze'){calls.push({name,args});throw new Error('vision unavailable');}return normalInvoke(name,args);};
calls.length=0;
page=render('daily');
await find(page,n=>n.type==='button'&&n.props['data-action']==='screen').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.equal(calls.filter(c => ['hide', 'show'].includes(c.name)).length, 0, 'native selection owns window restoration on failure');
globalThis.__desktopInvoke=async(name,args)=>{ if(name==='companion_screen_analyze'){calls.push({name,args});return {cancelled:true};} return normalInvoke(name,args); };
calls.length=0;
page=render('daily');
await find(page,n=>n.type==='button'&&n.props['data-action']==='screen').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.equal(calls.filter(c=>c.name==='emit').length,0,'cancelled selection never produces analysis or a chat message');
globalThis.__desktopInvoke=async(name,args)=>{ if(name==='companion_screen_analyze'){calls.push({name,args});return {saved_path:'C:/Users/Test/Pictures/Screenshots/selected.png'};} return normalInvoke(name,args); };
calls.length=0;
page=render('daily');
await find(page,n=>n.type==='button'&&n.props['data-action']==='screen').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.equal(calls.filter(c=>c.name==='emit' && c.args[0]==='chat:assistant_message').length,0,'save-only does not fabricate an AI chat reply');
assert.ok(calls.some(c=>c.name==='emit' && c.args[0]==='companion:interaction' && c.args[1].content.includes('系统截图目录')),'save-only confirms where the screenshot went');
globalThis.__desktopInvoke=normalInvoke;
calls.length=0;
page=render('daily','',{embedded:true,initialCharacter:'nana'});
assert.ok(page.props.className.includes('desktop-assistant-embedded'));
const interactionEffect=globalThis.__desktopEffects.at(-1);
const release=interactionEffect();
assert.deepEqual(calls.find(c=>c.name==='ensure_chat_interactive')?.args,undefined,'entering the assistant enables clicks before any field gets focus');
assert.equal(page.props.onBlurCapture,undefined,'blurring a button or field must not make the whole assistant click-through');
assert.equal(page.props.onFocusCapture,undefined,'interaction is owned by the page lifecycle, not individual fields');
release();
const releaseAgain=interactionEffect();
assert.deepEqual(calls.filter(c=>c.name==='ensure_chat_interactive').length,3,'StrictMode setup/cleanup/setup ends with an interactive window');
releaseAgain();
assert.equal(calls.at(-1).name,'ensure_chat_interactive','leaving the assistant keeps chat interactive');
calls.length=0;
render('daily');
globalThis.__desktopEffects.at(-1)()?.();
assert.equal(calls.length,0,'standalone rendering does not alter the chat sidebar');
page=render('daily');
assert.equal(find(page,n=>n.type==='textarea'),null,'overview opens tools instead of displaying every form');
assert.equal(find(page,n=>n.props?.role==='group'&&n.props['aria-label']==='选择角色'),null,'assistant inherits its character context without a role picker');
assert.equal(find(page,n=>n.type==='img'),null,'assistant overview has no decorative illustrations');
assert.equal(find(page,n=>n.type==='nav'),null,'grouped overview does not add redundant bottom navigation');
find(page,n=>n.type==='button'&&n.props['data-action']==='notes').props.onClick();
assert.ok(globalThis.__desktopUpdates.includes('notes'),'home note tile opens the dedicated editor');
page=render('tools');
assert.equal(find(page,n=>n.type==='button'&&text(n)==='偏好'),null);
assert.equal(find(page,n=>n.type==='button'&&text(n)==='语音诊断'),null);
const grid=find(page,n=>n.props?.className==='assistant-grid');
assert.deepEqual(grid.props.children.map(text),['随手记','截图分析','快捷启动','小游戏']);
assert.equal(grid.props.children[3].props.className,'assistant-tile');
calls.length=0;
await find(page,n=>n.type==='button'&&text(n)==='设置').props.onClick();
await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(calls.find(c=>c.name==='emit').args,['tray:menu_action',{action:'settings',character_id:'nana'}]);

globalThis.window=oldWindow;if(oldCrypto)Object.defineProperty(globalThis,'crypto',oldCrypto);else delete globalThis.crypto;
delete globalThis.__desktopStates;delete globalThis.__desktopEffects;delete globalThis.__desktopUpdates;delete globalThis.__desktopCalls;delete globalThis.__desktopInvoke;
console.log('Desktop actions: click-only screenshot, user-owned quick notes, character preferences, local games and failed vision window recovery passed');
