import assert from 'node:assert/strict';
import { createAsyncCache } from '../src/components/settings/asyncCache.ts';
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => { resolve=a;reject=b; }); return {promise,resolve,reject}; };
const requests = [];
const cache = createAsyncCache(() => { const request=deferred();requests.push(request);return request.promise; });
const old = cache.get();
assert.equal(cache.get(), old);
await Promise.resolve();
let changes=0;
const dispose=cache.subscribe(() => changes++);
cache.invalidate();
const fresh=cache.get();
await Promise.resolve();
requests[1].resolve('new');
assert.equal(await fresh, 'new');
requests[0].resolve('stale');
assert.equal(await old, 'new');
assert.equal(await cache.get(), 'new');
assert.equal(changes,1);
dispose();cache.invalidate();
const failed=cache.get();await Promise.resolve();requests[2].reject(new Error('offline'));
await assert.rejects(failed,/offline/);
const retry=cache.get();await Promise.resolve();requests[3].resolve('recovered');
assert.equal(await retry,'recovered');
assert.equal(changes,1);
console.log('Settings cache: shared loads, stale response rejection, subscription cleanup and failure retry passed.');
