import assert from 'node:assert/strict';
import { buildSync } from 'esbuild';
const bundle = buildSync({ entryPoints: ['src/components/mind-inspector/pages/workbenchSnapshot.ts'], bundle: true, write: false, format: 'esm', platform: 'node' });
const { readWorkbenchSnapshot } = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
let stored = null;
globalThis.localStorage = { getItem: () => stored };
assert.equal(readWorkbenchSnapshot().rightTab, 'overview');
stored = JSON.stringify({ activeId: 'session-a', input: '未发送草稿', rightTab: 'preview', previewTabs: [{ path: 'C:/docs/report.md', key: 'report' }], activePreview: 'C:/docs/report.md', previewFullView: true, sessionView: 'flat', sessionSort: 'manual', workspaceTreeOpen: false, scroll: { '.md-live': 550 } });
const restored = readWorkbenchSnapshot();
assert.equal(restored.activeId, 'session-a');
assert.equal(restored.input, '未发送草稿');
assert.equal(restored.activePreview, 'C:/docs/report.md');
assert.equal(restored.previewFullView, true);
assert.equal(restored.scroll['.md-live'], 550);
assert.equal(restored.workspaceTreeOpen, false);
stored = JSON.stringify({ rightTab: 'invalid', previewFullView: true, previewTabs: [null, { path: 12 }], scroll: { a: -1, b: 'x', c: 10 } });
assert.deepEqual(readWorkbenchSnapshot().previewTabs, []);
assert.equal(readWorkbenchSnapshot().previewFullView, false);
assert.deepEqual(readWorkbenchSnapshot().scroll, { c: 10 });
stored = '{broken';
assert.equal(readWorkbenchSnapshot().activeId, null);
globalThis.localStorage.getItem = () => { throw new Error('disabled'); };
assert.equal(readWorkbenchSnapshot().input, '');
console.log('Workbench snapshot: state restoration, invalid data and unavailable storage passed.');
