//! 英文情绪语料库（14 类 × 24 条 = 336 条）
//!
//! 与中文语料库 CORPUS_ZH 对等，覆盖相同的 14 类情绪和场景维度。

use super::embedding_classifier::{CorpusEntry, EmotionContext, EmotionTarget};

pub static CORPUS_EN: &[CorpusEntry] = &[
    // happy (24)
    CorpusEntry { text: "slow morning, loving it", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "afternoon nap hit the spot", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "playlist is hitting different", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "coworker brought homemade cookies", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "your outfit suggestion worked great", emotion: "happy", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "having you around feels safe", emotion: "happy", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "our chats make time fly", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "you picked up new words, cute", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "having friends around feels warm", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "family being close is everything", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "she got me a little gift, so sweet", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "this relationship gives me peace", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "work went smoothly today", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "clean desk, clean mind", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "coworker helped me crack a problem", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the data you pulled was super helpful", emotion: "happy", target: EmotionTarget::Ai, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "did a yoga set, so relaxed", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "deep breaths calmed me right down", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "tried a new cafe, loved it", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "fireworks were unreal", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "stream hit a new peak today, hyped", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "emote spam is cracking me up", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "ranked up today, let's go", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "squad carried hard", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::Gaming },

    // excited (24)
    CorpusEntry { text: "counting down the days", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "hyped for the weekend", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "new episode's out", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "cousin bought a house", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "your recommendation got me hyped", emotion: "excited", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "you make every topic exciting", emotion: "excited", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "can't wait to tell you about my day", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "your reactions make everything better", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "seeing him tonight, can't wait", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "anniversary's coming up", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "my friend just told me she's pregnant", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "our trip is finally happening", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "project got approved", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "new office looks sick", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "my manager gave me a lead role", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the outline you made saved me", emotion: "excited", target: EmotionTarget::Ai, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "blood test came back clean", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "recovery's going faster than expected", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "movie premiere was wild", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "fireworks lasted forever", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "going live in 10, hyped", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "new overlay looks slick", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "got the rare drop", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "my squad wiped the lobby", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::Gaming },

    // grateful (24)
    CorpusEntry { text: "I'm so grateful", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "you made my day", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the universe came through", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "friend dropped off groceries", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "your help meant a lot", emotion: "grateful", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "thanks for not judging me", emotion: "grateful", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I'm lucky to have you", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "the late-night talks heal", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "they've been my rock", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "he remembered the little things", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "they had my back", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "every moment with them", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "I'm thankful for the opportunity", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the launch went smoothly", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "prof wrote me a rec", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "thankful for my health", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the workout's paying off", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "doc caught it early", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the surprise party was perfect", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the lineup was incredible", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "the community's amazing", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "the sub bomb was unreal", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "you're a lifesaver", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the event rewards are generous", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // sad (24)
    CorpusEntry { text: "just want to cry", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "I feel empty", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the photos got me nostalgic", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "grandma's not doing well", emotion: "sad", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "wish you were here", emotion: "sad", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "you wouldn't understand", emotion: "sad", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I opened up to you and feel worse", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "your voice feels distant", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "we're drifting apart", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "I'm alone on this", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "they left me on read", emotion: "sad", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "love feels one-sided", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "got let go today", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the empty office feels heavy", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "boss took my project away", emotion: "sad", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "I'm exhausted all the time", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "I'm losing myself", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the scale won't budge", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "moving away from here", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the song reminded me of loss", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "I'm talking to nobody", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "highlights got no views", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "I lost my save file", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the server's shutting down", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // frustrated (24)
    CorpusEntry { text: "I keep hitting walls", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "nothing's going right", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the form keeps erroring", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "coworker's slowing us down", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "your answer doesn't help", emotion: "frustrated", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "this isn't working", emotion: "frustrated", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I'm burnt out", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "your responses are looping", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "we keep fighting", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "I'm exhausted by this", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "my friend keeps flaking", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "we keep having the same fight", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "stuck on the same bug", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the doc's unclear", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "teammate's blocking me", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "your explanation confused me more", emotion: "frustrated", target: EmotionTarget::Ai, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "meds aren't working", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the app's confusing", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "I forgot my keys", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "everything's sold out", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "stream keeps buffering", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "alerts aren't firing", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "I keep dying", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "smurf in my lobby", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::Gaming },

    // anxious (24)
    CorpusEntry { text: "my heart's racing", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "my mind won't shut off", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the late night's not helping", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "friend's going through a crisis", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "are you okay, you're quiet", emotion: "anxious", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "am I weird for relying on you", emotion: "anxious", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I'm scared to lose this", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "the screen glitching scares me", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "what if he leaves", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "she's pulling away, I can feel it", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "they haven't been themselves", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "every wait feels like forever", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "what if I fail", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the stack of unread emails", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "client's unhappy", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "what if it's serious", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the palpitations won't stop", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "doc's face looked grim", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the crowd's got me on edge", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the unfamiliar place is scary", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "viewers are dropping, I'm worried", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "the viewer count's fluctuating", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "I'm scared of deranking", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the ranked countdown", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // tired (24)
    CorpusEntry { text: "exhausted", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "brain's not working", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the dark room's making me sleepy", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "friend called at 3am", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "your questions drain me today", emotion: "tired", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "just gonna zone out", emotion: "tired", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I need to wind down", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "typing feels heavy tonight", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "tired of pretending", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "she's exhausting to deal with", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "the family gathering was tiring", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "small talk takes it out of me", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "exam season's draining", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "deadline week's brutal", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "client's demanding", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "my body's giving out", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "my eyes are heavy", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "doc's appointments wear me out", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "I overdid it", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the noise was overwhelming", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "4-hour stream drained me", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "modding's wearing me down", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "eyes are straining", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the matchmaking's slow tonight", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // angry (24)
    CorpusEntry { text: "I'm so done with this", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "seriously pissed right now", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "they raised the prices again", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "roommate left a mess", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "you're missing the point", emotion: "angry", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "you're not listening", emotion: "angry", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I'm losing my patience", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "your tone is pissing me off", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "he's pissing me off", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "she's pushing my buttons", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "my friend's ignoring me", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "nothing gets through", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "I hate this project", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the new policy is garbage", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "he threw me under the bus", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "your answer was misleading", emotion: "angry", target: EmotionTarget::Ai, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "can't get an appointment", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "forms are impossible", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "I want a refund", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "line was ridiculous", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "stream got raided by trolls", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "tools are bugged", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "matchmaking's a joke", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "my squad's trolling", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::Gaming },

    // disappointed (24)
    CorpusEntry { text: "I expected more", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "meh, that was underwhelming", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the movie's plot was thin", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "barista got my order wrong", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the answer missed the mark", emotion: "disappointed", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "I expected more from you", emotion: "disappointed", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I thought we had a moment", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "the chat feels scripted", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I expected better from her", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "she broke her promise", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "they didn't even try", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "the spark fizzled", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "grade was lower than expected", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the deal fell through", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "client backed out", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the scale went up again", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "lab results came back bad", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "trainer's advice was generic", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the food fest was mid", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the crowd was dead", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "the collab fell through", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "the merch sold out too fast", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "the dlc was overpriced", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the dev's response was tone-deaf", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::Gaming },

    // surprised (24)
    CorpusEntry { text: "I didn't see that coming", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "well that's a twist", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the power just went out", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "roommate cleaned the whole place", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "didn't expect that from you", emotion: "surprised", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "that's surprisingly insightful", emotion: "surprised", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I didn't see this coming", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "the sudden topic shift", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "didn't expect this from him", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "he proposed", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "they reconciled out of nowhere", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "the sudden confession", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "the test got pushed back", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the deadline moved up", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "prof extended the deadline", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "results came back clean", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the supplement actually worked", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "doc was wrong", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "didn't expect this turnout", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the venue's bigger than I thought", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "a huge creator raided me", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "the clip went viral", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "the twist ending", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the easter egg's unexpected", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // curious (24)
    CorpusEntry { text: "wonder what happened", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "who came up with this", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "what's that smell", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "where's my roommate", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "where'd you learn that", emotion: "curious", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "what else", emotion: "curious", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I want to know more about you", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "your answers are always interesting", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "wonder what he's thinking", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "why's he distant", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "they unfollowed me", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "our conversations shifted", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "what's the answer", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "what's the new policy", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "what's my boss thinking", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "can you walk me through it", emotion: "curious", target: EmotionTarget::Ai, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "how long to recover", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "what's pollen count", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "what's the event about", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "where's the venue", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "what's the stream about", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "what's the giveaway", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "what's the meta", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "who's on my team", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::Gaming },

    // neutral (24)
    CorpusEntry { text: "on the bus", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "it's Tuesday", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "traffic's normal today", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "coworker's on leave today", emotion: "neutral", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "you're pretty consistent", emotion: "neutral", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "what's up with you", emotion: "neutral", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "just checking in", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "you responded fast", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "my friend's usual spot", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "family dinner tonight", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "my friend's in town", emotion: "neutral", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "meeting up later", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "working on the report", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "project deadline's Friday", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "teammate's on vacation", emotion: "neutral", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "you gave the answer", emotion: "neutral", target: EmotionTarget::Ai, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "cooking dinner", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "gym's open till 10", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "walked around downtown", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "lineup's posted", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "going live soon", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "chat's chill tonight", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "loading the map", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "friend's online", emotion: "neutral", target: EmotionTarget::Other, context: EmotionContext::Gaming },

    // bored (24)
    CorpusEntry { text: "this is dull", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "I need something to do", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the news is repetitive", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "roommate's been on repeat", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "give me something interesting", emotion: "bored", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "this is getting old", emotion: "bored", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I've got nothing", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "the conversation's stalled", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "this is getting stale", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "he's always on his phone", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "they always want to do the same thing", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "every weekend's the same", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "nothing to do at work", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the syllabus is dull", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "boss is monotonous", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "this routine's stale", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "stuck in bed, bored", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "trainer's routine's dull", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the museum was meh", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the venue had no vibe", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "chat's quiet", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "the alerts feel stale", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "nothing new to do", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the dialogue's repetitive", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // confused (24)
    CorpusEntry { text: "I'm lost", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "can you explain again", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "the layout's confusing", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "roommate's explanation was a mess", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "can you simplify that", emotion: "confused", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "I'm lost in your explanation", emotion: "confused", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "I'm not sure what I feel", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "your responses don't match my questions", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "the relationship's unclear", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "she's hot and cold", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "they're not making sense", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "the signals are crossed", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "the lecture went over my head", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "the new tool's confusing", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "prof's explanation was muddy", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "I don't get the diagnosis", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "the symptoms don't match anything", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "doc's explanation was hazy", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "I don't get the lineup", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "the announcements are unclear", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "I don't get the new setup", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "the mod tools are convoluted", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "the objective's unclear", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "the map's a maze", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

];






