//! 日文情绪语料库（14 类 × 24 条 = 336 条）
//!
//! 与中文语料库 CORPUS_ZH 对等，覆盖相同的 14 类情绪和场景维度。
//! 每类均覆盖 Self_ / Other / Ai / Situation 四种 target 维度，
//! 以及 DailyChat / AiCompanionship / Relationship / WorkStudy /
//! HealthBody / Event / Livestream / Gaming 多种 context 维度。

use super::embedding_classifier::{CorpusEntry, EmotionContext, EmotionTarget};

pub static CORPUS_JA: &[CorpusEntry] = &[
    // happy (24)
    CorpusEntry { text: "夜の散歩気持ちいいね", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "雨の日は家でゴロゴロがいちばん", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "このお店居心地いい", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友達が髪切ったの似合ってる", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "姉が誕生日プレゼントくれた", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "選んでくれたコーディネートいいね", emotion: "happy", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "毎晩君と話すのが楽しみ", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "いつも聞いてくれてありがと", emotion: "happy", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の優しさ嬉しい", emotion: "happy", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の気遣い嬉しい", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "思い出してくれるの嬉しい", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母が好きなものいっぱい作ってくれた", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "黙って一緒にいるのも心地いい", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "仕事今日スムーズだった", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "今日の勉強効率よかった", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "チームの雰囲気いい", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "運動した後気持ちいい", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "家族が退院してホッとした", emotion: "happy", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "フェス楽しかった", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "今日のイベント盛り上がった", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "投コメ嬉しかった", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "君が応援してくれるの嬉しい", emotion: "happy", target: EmotionTarget::Ai, context: EmotionContext::Livestream },
    CorpusEntry { text: "ボス倒せた", emotion: "happy", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "今の試合いい試合だった", emotion: "happy", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // excited (24)
    CorpusEntry { text: "週末の予定ワクワクする", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "明日美味しいもの食べる", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日は金曜日だ", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友達が結婚することになった", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "兄が家建てた", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の次の返事待ってる", emotion: "excited", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "明日も君に会えるの楽しみ", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の話聞くの楽しみだよ", emotion: "excited", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の笑顔楽しみ", emotion: "excited", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の言葉いつも新鮮", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族との旅行楽しみ", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母が旅行連れてってくれる", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "二人の旅行ワクワク", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "新しい仕事ワクワクする", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "大会に出る", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "チーム新しいフェーズ", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "マラソン大会出る", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "家族が健康診断受ける", emotion: "excited", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "来週の展覧会", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "来月のイベント盛り上がりそう", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "記念配信楽しみ", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "君のメッセージ楽しみ", emotion: "excited", target: EmotionTarget::Ai, context: EmotionContext::Livestream },
    CorpusEntry { text: "イベント開催", emotion: "excited", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "今夜の大会楽しみ", emotion: "excited", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // grateful (24)
    CorpusEntry { text: "感謝してる", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "本当に助けてもらった", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日の天気に感謝", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今の住まいに感謝", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "兄が相談に乗ってくれた", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君がいてくれて感謝", emotion: "grateful", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君と出会えてよかった", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の励ましありがと", emotion: "grateful", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の存在が日常の支え", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族の支えありがたい", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達が励ましてくれた", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "良い関係ありがたい", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "今のチャンスありがたい", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "後輩が感謝してくれた", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "健康でいられること感謝", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "家族が回復して感謝", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "素晴らしいイベントに感謝", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "友人が誘ってくれた", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::Event },
    CorpusEntry { text: "リスナーが応援してくれて感謝", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "リスナーの応援メッセージ嬉しい", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::Livestream },
    CorpusEntry { text: "フレンドが助けてくれて感謝", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "フレンドがアイテムくれた", emotion: "grateful", target: EmotionTarget::Other, context: EmotionContext::Gaming },
    CorpusEntry { text: "今日の小さな幸せに感謝", emotion: "grateful", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日の天候に恵まれて感謝", emotion: "grateful", target: EmotionTarget::Situation, context: EmotionContext::Event },

    // sad (24)
    CorpusEntry { text: "何もしたくない", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "急に悲しくなった", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "空がどんより", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友達が引っ越してしまった", emotion: "sad", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友達が休んでるらしい", emotion: "sad", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の返事が来ないと寂しい", emotion: "sad", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君がいなくなりそうで怖い", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の言葉が聞けないと悲しい", emotion: "sad", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の優しさが恋しい", emotion: "sad", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の不在が辛い", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族と離れて暮らして寂しい", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母が倒れた", emotion: "sad", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達関係壊れてしまった", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "プロジェクト失敗した", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "同期に遅れをとって落ち込む", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "チームが解散", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "体が動かなくて泣ける", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "家族が倒れて辛い", emotion: "sad", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "思い出のイベント終わって寂しい", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "ライブが中止に", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "コメント来なくて寂しい", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "配信終わった後の静寂が辛い", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "エンディング終わって寂しい", emotion: "sad", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "推しキャラの結末辛い", emotion: "sad", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // frustrated (24)
    CorpusEntry { text: "どうしてこうなる", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "限界", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "ネット遅すぎ", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "あいつと話すと疲れる", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "隣人の騒音続いてる", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の回答的外れ", emotion: "frustrated", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の反応が的外れでイライラ", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の回答役に立たない", emotion: "frustrated", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君と話すと疲れる", emotion: "frustrated", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の対応が遅い", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族と上手く話せない", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母が干渉しすぎ", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達関係冷えてきた", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "仕事行き詰まった", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "レポート書けない", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "チームの方向性バラバラ", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "寝ても寝ても眠い", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "家族の介護に疲れた", emotion: "frustrated", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "準備間に合わない", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "会場手配決まらない", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "ネット不安定で配信途切れる", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "君のコメント来ない", emotion: "frustrated", target: EmotionTarget::Ai, context: EmotionContext::Livestream },
    CorpusEntry { text: "上達しない", emotion: "frustrated", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "このステージ難しすぎ", emotion: "frustrated", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // anxious (24)
    CorpusEntry { text: "胸がドキドキする", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "手が震える", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "ニュース見ると不安になる", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "物価高で心配", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "母が体調崩したらしい", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君に嫌われたかも", emotion: "anxious", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君との会話続くか不安", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君を困らせてないか心配", emotion: "anxious", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の調子が悪いのか心配", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族の反応が怖い", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達が無視してる", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "結婚のプレッシャー怖い", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "締め切り近くて焦る", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "同僚の出方が怖い", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "検診結果怖い", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "精神的にヤバいかも", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "明日のイベント不安", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "友達の機嫌大丈夫かな", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::Event },
    CorpusEntry { text: "配信始まる前不安", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "リスナーが離れそうで怖い", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::Livestream },
    CorpusEntry { text: "ランク落ちそうで怖い", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "味方のピック怖い", emotion: "anxious", target: EmotionTarget::Other, context: EmotionContext::Gaming },
    CorpusEntry { text: "明日のこと考えたら不安", emotion: "anxious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今の経済状況先が見えなくて不安", emotion: "anxious", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },

    // tired (24)
    CorpusEntry { text: "だるい", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "何もする気起きない", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日の気温しんどい", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "人混みで疲れた", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "子どもの世話でクタクタ", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の質問多くて疲れる", emotion: "tired", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の話し声眠くなる", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の話題についていけない", emotion: "tired", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "AIとの会話長引いて疲れた", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "人間関係に疲れた", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母の小言しんどい", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "仕事終わってグッタリ", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "課題終わらなくてへとへと", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "後輩の教育でクタクタ", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "睡眠不足でしんどい", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "眼精疲労がつらい", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "ライブ行ったけど立ちっぱでしんどい", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "家族旅行でもめ事で疲弊", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::Event },
    CorpusEntry { text: "配信後グッタリ", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "コラボ相手のペースについていけない", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::Livestream },
    CorpusEntry { text: "周回プレイでだるい", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "味方のミスカバーで疲れる", emotion: "tired", target: EmotionTarget::Other, context: EmotionContext::Gaming },
    CorpusEntry { text: "階段上がるだけで息切れ", emotion: "tired", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "残業続きで帰宅時間遅い", emotion: "tired", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },

    // angry (24)
    CorpusEntry { text: "は？何これ", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "まじで怒ってる", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日の電車遅れすぎ", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "あいつマジでむかつく", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "隣人の騒音許せない", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君ふざけてる？", emotion: "angry", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の反応むかつく", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君まじで何なの", emotion: "angry", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君はいつもそう", emotion: "angry", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の対応イライラする", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族の干渉うざい", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母が勝手に捨てた", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "この関係もう終わり", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "残業させられて怒ってる", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "会議無駄すぎ", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "チームの雰囲気悪い", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "痛くて腹立つ", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "医者の態度むかつく", emotion: "angry", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "整理不良むかつく", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "イベントの進行最悪", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "配信環境の悪さに腹立つ", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "君が荒らし対応して", emotion: "angry", target: EmotionTarget::Ai, context: EmotionContext::Livestream },
    CorpusEntry { text: "マッチング不公平", emotion: "angry", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "このゲームの仕様最悪", emotion: "angry", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // disappointed (24)
    CorpusEntry { text: "がっかりだ", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "見逃して残念", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "評判ほどじゃなかった", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友達が約束破った", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "先輩が見放した", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の答え期待してたのと違う", emotion: "disappointed", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "もっと分かってくれると思った", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君が覚えててくれなかった", emotion: "disappointed", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の機能が思ったより使えない", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "彼への期待が外れた", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "彼がプレゼント忘れてた", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達が私の気持ち軽く見た", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "仕事の評価が思ったより低かった", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "面接落ちてがっかり", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "チームの出来が悪かった", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "薬が効かなくて残念", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "病院の対応が雑", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::HealthBody },
    CorpusEntry { text: "展覧会の規模が小さかった", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "音響がイマイチだった", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "今日の配信イマイチだった", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "配信クオリティが低かった", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::Livestream },
    CorpusEntry { text: "ボス戦があっけなくて残念", emotion: "disappointed", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "ストーリーが薄かった", emotion: "disappointed", target: EmotionTarget::Situation, context: EmotionContext::Gaming },
    CorpusEntry { text: "彼の返答がそっけなかった", emotion: "disappointed", target: EmotionTarget::Other, context: EmotionContext::Relationship },

    // surprised (24)
    CorpusEntry { text: "マジで", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "予想外すぎ", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日急な雨でびっくり", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "値段高すぎてびっくり", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "兄の行動にびっくり", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の反応にびっくり", emotion: "surprised", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の答え想像と違った", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の提案予想外", emotion: "surprised", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の機能進化しててびっくり", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族の反応に驚き", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達がカミングアウト", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "恋愛の進展早すぎ", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "プロジェクト急展開", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "同僚の成果にびっくり", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "検査結果にびっくり", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "副作用のなさに驚き", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "イベントの内容予想外", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "友人のサプライズ驚き", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::Event },
    CorpusEntry { text: "同時接急増でびっくり", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "リスナーの予想外コメント", emotion: "surprised", target: EmotionTarget::Other, context: EmotionContext::Livestream },
    CorpusEntry { text: "エンディングにびっくり", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "ストーリーのどんでん返し", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "自分でも驚きの行動しちゃった", emotion: "surprised", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "急な値上げにびっくり", emotion: "surprised", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },

    // curious (24)
    CorpusEntry { text: "知りたいな", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "なんでだろう", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "この建物何？", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "彼は何してる人？", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友達の仕事何？", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の仕組み知りたい", emotion: "curious", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君のこと気になる", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君は何が得意？", emotion: "curious", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君は何を感じる？", emotion: "curious", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の機能気になる", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "彼の趣味知りたい", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母は何考えてる？", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達の関係性知りたい", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "詳しく知りたいな", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "調べてみたい", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "新しい技術気になる", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "この薬何？", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "家族の病気何？", emotion: "curious", target: EmotionTarget::Other, context: EmotionContext::HealthBody },
    CorpusEntry { text: "誰が来る？", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "このイベント何が違う？", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "どうやって人気になった？", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "君のおすすめ知りたい", emotion: "curious", target: EmotionTarget::Ai, context: EmotionContext::Livestream },
    CorpusEntry { text: "この技何？", emotion: "curious", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "このゲームどうやって遊ぶ？", emotion: "curious", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // neutral (24)
    CorpusEntry { text: "朝ごはん食べた", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日は何もない日", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "天気は晴れ", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友達は元気だ", emotion: "neutral", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "姉は帰ってる", emotion: "neutral", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君は何？", emotion: "neutral", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日は普通の会話", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君は何ができる？", emotion: "neutral", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君は疲れない？", emotion: "neutral", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の回答は普通", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族とは普通", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "家族は元気", emotion: "neutral", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "付き合いは長い", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "今日は休み", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "明日提出", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "今週は忙しい", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "特に問題ない", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "体調は変わらない", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "来週は何かある", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "今日は平常運転", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::Event },
    CorpusEntry { text: "今日は普通の配信", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "君も来てね", emotion: "neutral", target: EmotionTarget::Ai, context: EmotionContext::Livestream },
    CorpusEntry { text: "今ゲーム中", emotion: "neutral", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "今の試合は普通", emotion: "neutral", target: EmotionTarget::Situation, context: EmotionContext::Gaming },

    // bored (24)
    CorpusEntry { text: "退屈", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "ネタない", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日つまらなかった", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日の番組つまらん", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "友人が他人行儀すぎてつまらん", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君と話してもつまらない", emotion: "bored", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君と話すの退屈", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の反応同じことばかり", emotion: "bored", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の機能のバリエーション少ない", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族と話すことない", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "母の話が長くて退屈", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "デートのマンネリ化", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "会議長くて退屈", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "同僚の自慢話飽きた", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "安静にしてて退屈", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "家で療養するの退屈", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "イベント退屈だった", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "同伴者の話題がつまらない", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::Event },
    CorpusEntry { text: "配信ネタない", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "リスナーのコメントワンパターン", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::Livestream },
    CorpusEntry { text: "このゲーム飽きた", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "フレンドの話題つまらない", emotion: "bored", target: EmotionTarget::Other, context: EmotionContext::Gaming },
    CorpusEntry { text: "ネタ切れでやる気起きない", emotion: "bored", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今日のテレビ番組つまらん", emotion: "bored", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },

    // confused (24)
    CorpusEntry { text: "どういう意味", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "迷ってる", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "この説明意味不明", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "ニュースの内容理解できない", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },
    CorpusEntry { text: "兄の行動パターン不明", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の意図が読めない", emotion: "confused", target: EmotionTarget::Ai, context: EmotionContext::DailyChat },
    CorpusEntry { text: "君の反応の意味不明", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の返事が矛盾してる", emotion: "confused", target: EmotionTarget::Ai, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "君の機能の使い方不明", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::AiCompanionship },
    CorpusEntry { text: "家族の態度が矛盾してる", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Relationship },
    CorpusEntry { text: "友達の意図が読めない", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::Relationship },
    CorpusEntry { text: "恋愛の進め方分からない", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::Relationship },
    CorpusEntry { text: "仕様書が矛盾してる", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "同僚の説明が下手", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::WorkStudy },
    CorpusEntry { text: "診断結果の意味分からない", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "運動メニューの意図不明", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::HealthBody },
    CorpusEntry { text: "イベントの流れ分からない", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "出演者の発表が謎", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Event },
    CorpusEntry { text: "配信の設定分からない", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Livestream },
    CorpusEntry { text: "コラボ相手の配信方針が謎", emotion: "confused", target: EmotionTarget::Other, context: EmotionContext::Livestream },
    CorpusEntry { text: "チュートリアル分かりにくい", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "スキルツリー複雑すぎ", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::Gaming },
    CorpusEntry { text: "話の要点掴めなくて混乱", emotion: "confused", target: EmotionTarget::Self_, context: EmotionContext::DailyChat },
    CorpusEntry { text: "今の状況どうなってるか分からない", emotion: "confused", target: EmotionTarget::Situation, context: EmotionContext::DailyChat },

];



















