const zh = {
  title: '本地调用用量', source: 'API 返回 · 本地记录', subtitle: '从真实响应出发，了解用量花在了哪里。',
  days: '天', today: '今天', refresh: '刷新', refreshing: '读取中…', updated: '更新于',
  trend: '趋势总览', models: '模型', routes: '任务路由', tasks: '用途分类',
  tokens: 'Token', requests: '已记录调用', total: '记录 Token 总量', calls: '已记录调用', cacheShare: '缓存读取占输入', activeModels: '使用过的模型',
  tokenNote: '含输入、输出与缓存', callsNote: '仅统计返回非零用量的调用', cacheNote: '按已记录输入 Token 计算', modelNote: '按响应对应的模型名称',
  input: '非缓存输入', output: '输出', hit: '缓存读取', cache_creation: '缓存创建',
  daily: '每日用量', composition: 'Token 构成', noDay: '当天没有用量记录', date: '日期', recorded: '记录',
  empty: '这个时间段还没有用量记录', emptyHelp: '模型返回用量后会自动累积到这里。没有记录不代表平台没有产生用量。',
  loading: '正在读取本地用量记录…', error: '无法读取用量记录', errorHelp: '请重试。读取失败时不会用零值替代数据。',
  retry: '重试', stale: '刷新失败，以下保留上次成功读取的数据。',
  scope: '统计范围', scopeHelp: '只包含本应用采集到的 API 用量；未上报用量的请求不计入。这不是平台账单，不估算费用。不同模型的 Token 数量按各服务返回值累计。',
  ranking: '用量分布', detail: '明细', searchModels: '搜索模型名称', searchRoutes: '搜索路由', searchTasks: '搜索用途', noMatch: '没有匹配的记录',
  share: '占所选时间段', all: '全部记录', back: '取消选择', selected: '当前审阅', totalColumn: '总 Token', requestColumn: '调用',
  legacy: '历史未归属', unknownModel: '未归属模型', unknownRoute: '未归属路由', unknownTask: '未归属用途',
  coverage: '路由归属覆盖', coverageHelp: '精确路由记录从此次更新后开始；历史记录不会根据当前路由配置补算。',
  taskCoverage: '用途归属覆盖', taskCoverageHelp: '旧记录可能只有总量；未归属部分也计入总量。',
  matrix: '路由 × 实际模型', matrixHelp: '单元格显示真实观测到的调用，包括回退模型。点击可审阅该组合的每日用量。',
  noMatrix: '尚无可追溯到具体路由的模型记录。新的调用会逐步填充此矩阵。',
  routeHelp: '这里展示请求的任务路由；用途分类单独展示调用目的，两者可能不同。',
  modelHelp: '同名模型合并显示；历史记录没有服务商或 API Key 的独立维度。',
  choose: '选择记录查看每日趋势与完整 Token 明细',
  export: '导出明细 CSV', exportFailed: '导出失败，请重试。',
  purpose: { current_thought: '当前想法', proactive_channel: '主动消息渠道判断', proactive_message: '主动消息正文', proactive_share: '主动分享', unattributed: '未归属用途' } as Record<string, string>,
};
const en: typeof zh = {
  title: 'Local API usage', source: 'API-reported · local records', subtitle: 'See where your recorded model usage goes.',
  days: 'days', today: 'Today', refresh: 'Refresh', refreshing: 'Refreshing…', updated: 'Updated',
  trend: 'Overview', models: 'Models', routes: 'Routes', tasks: 'Purposes',
  tokens: 'Tokens', requests: 'Recorded calls', total: 'Recorded tokens', calls: 'Recorded calls', cacheShare: 'Cached share of input', activeModels: 'Models used',
  tokenNote: 'Input, output and cache included', callsNote: 'Calls reporting nonzero usage only', cacheNote: 'Based on recorded input tokens', modelNote: 'Grouped by model name',
  input: 'Uncached input', output: 'Output', hit: 'Cache reads', cache_creation: 'Cache creation',
  daily: 'Daily usage', composition: 'Token composition', noDay: 'No usage recorded for this day', date: 'Date', recorded: 'Recorded',
  empty: 'No usage recorded in this period', emptyHelp: 'Usage accumulates when a model reports it. No records does not mean no platform usage.',
  loading: 'Reading local usage records…', error: 'Cannot read usage records', errorHelp: 'Please retry. Failed reads are never replaced with zeros.',
  retry: 'Retry', stale: 'Refresh failed. Showing the last successfully loaded data.',
  scope: 'Coverage', scopeHelp: 'Only API usage captured by this app is included. Calls without reported usage are excluded. This is not a platform bill or cost estimate. Each service supplies its own token counts.',
  ranking: 'Usage distribution', detail: 'Details', searchModels: 'Search model names', searchRoutes: 'Search routes', searchTasks: 'Search purposes', noMatch: 'No matching records',
  share: 'of selected period', all: 'All records', back: 'Clear selection', selected: 'Reviewing', totalColumn: 'Total tokens', requestColumn: 'Calls',
  legacy: 'Historical, unattributed', unknownModel: 'Unknown model', unknownRoute: 'Unattributed route', unknownTask: 'Unattributed purpose',
  coverage: 'Route attribution coverage', coverageHelp: 'Exact route attribution starts with this update. Historical usage is never inferred from current settings.',
  taskCoverage: 'Purpose attribution coverage', taskCoverageHelp: 'Older records may only have totals. Unattributed usage remains in the overall total.',
  matrix: 'Route × observed model', matrixHelp: 'Cells show observed usage, including fallback models. Select a cell to review its daily usage.',
  noMatrix: 'No model usage can be traced to a specific route yet. New calls will populate this matrix.',
  routeHelp: 'Routes describe the requested model task; purposes describe why it was called. They can differ.',
  modelHelp: 'Models with the same name are combined. Historical records do not distinguish providers or API keys.',
  choose: 'Select a row to review daily usage and all token categories',
  export: 'Export details CSV', exportFailed: 'Export failed. Please retry.',
  purpose: { current_thought: 'Current thought', proactive_channel: 'Proactive channel decision', proactive_message: 'Proactive message', proactive_share: 'Proactive sharing', unattributed: 'Unattributed purpose' },
};
const ja: typeof zh = { ...en,
  title: 'ローカル API 使用量', source: 'API の報告値 · ローカル記録', subtitle: '記録されたモデル使用量の内訳を確認できます。',
  days: '日', today: '今日', refresh: '更新', refreshing: '読込中…', updated: '更新時刻',
  trend: '概要', models: 'モデル', routes: 'ルート', tasks: '用途',
  total: '記録トークン数', calls: '記録された呼び出し', requests: '記録された呼び出し', cacheShare: '入力のキャッシュ割合', activeModels: '使用モデル数',
  input: '非キャッシュ入力', output: '出力', hit: 'キャッシュ読取', cache_creation: 'キャッシュ作成',
  daily: '日別使用量', composition: 'トークン構成', empty: 'この期間の使用量記録がありません',
  searchModels: 'モデル名を検索', searchRoutes: 'ルートを検索', searchTasks: '用途を検索',
  all: 'すべての記録', back: '選択解除', selected: '確認中', scope: '集計範囲',
  legacy: '過去の未分類記録', unknownModel: '不明なモデル', unknownRoute: '未分類ルート', unknownTask: '未分類用途',
  matrix: 'ルート × 実際のモデル', export: 'CSV を出力',
  tokenNote: '入力、出力とキャッシュを含む', callsNote: 'ゼロ以外の使用量を報告した呼び出しのみ',
  cacheNote: '記録された入力トークンで計算', modelNote: 'モデル名で集計',
  noDay: 'この日の使用量記録はありません', date: '日付', recorded: '記録',
  emptyHelp: 'モデルが使用量を報告すると自動で記録されます。記録がないことは、プラットフォームの使用量がないことを意味しません。',
  loading: 'ローカル使用量を読み込み中…', error: '使用量を読み込めません', errorHelp: '再試行してください。読込エラーをゼロとして表示しません。',
  retry: '再試行', stale: '更新に失敗しました。最後に読み込めたデータを表示しています。',
  scopeHelp: 'このアプリが取得した API 使用量のみを含みます。使用量を報告しないリクエストは対象外です。請求額や費用の推定ではありません。トークン数は各サービスの報告値です。',
  ranking: '使用量分布', detail: '詳細', noMatch: '一致する記録がありません',
  share: '選択期間の割合', totalColumn: '合計トークン', requestColumn: '呼び出し',
  coverage: 'ルート分類の網羅率', coverageHelp: '正確なルート記録は今回の更新以降からです。過去の使用量を現在の設定から推測しません。',
  taskCoverage: '用途分類の網羅率', taskCoverageHelp: '過去の記録は合計のみの場合があります。未分類の使用量も全体に含まれます。',
  matrixHelp: '実際に観測したモデルの使用量を表示します。フォールバックも含みます。セルを選ぶと日別使用量を確認できます。',
  noMatrix: 'まだ具体的なルートとモデルに紐づく記録がありません。新しい呼び出しから表示されます。',
  routeHelp: 'ルートは要求されたモデルタスク、用途は呼び出しの目的です。両者が異なる場合があります。',
  modelHelp: '同名モデルは合算されます。過去の記録はプロバイダーや API キーを区別していません。',
  choose: '記録を選ぶと日別推移と全トークン内訳を確認できます', exportFailed: '出力に失敗しました。再試行してください。',
  purpose: { current_thought: '現在の思考', proactive_channel: '自発的メッセージの経路判断', proactive_message: '自発的メッセージ', proactive_share: '自発的な共有', unattributed: '未分類用途' },
};
export const usageCopy = { zh, en, ja };
export type UsageCopy = typeof zh;
